### ISSUE TITLE
Write not working

### ISSUE THREAD

**Issue by Kasuhikdas** [fh1ch/node-bacstack#105]
Node Version: v8.11.0

Node BACstack Version: 0.0.1-beta.13

I am trying to work with BACnet properties,
Who Is / I Am is working perfectly fine.
Read is also working using the following code snippet

const requestArray = [
    { objectId: { type: 21, instance: 6 }, properties: [{ id: 8 }] }
];
client.readPropertyMultiple('10.1.1.255', requestArray, (err, value) => {
    console.log('value: ', JSON.stringify(value));
    console.log('Error:',err);
});

But write is not working its having timeout error.
const values = [
    {
        objectId: { type: 21, instance: 6  }, values: [
            { property: { id: 75, index: 4294967295,}, value: [{ type: bacnet.enum.ApplicationTags.BACNET_APPLICATION_TAG_BOOLEAN, value: 100 }], priority: 8 }
        ]
    }
];
client.writePropertyMultiple('10.1.1.228', values, (err, value) => {
    console.log('value: ', value);
    console.log(err);
});

Any help will be much appreciated.

**Comment by fh1ch** [comment]
Hi @Kasuhikdas. See https://github.com/fh1ch/node-bacstack/blob/master/FAQ.md#i-receive-the-error-err_timeout-what-does-this-mean for more info regarding the timeout error. Also see https://github.com/fh1ch/node-bacstack/blob/master/FAQ.md#what-is-the-easiest-way-to-debug-failing-operations for more hints on how to debug such issues.

TL'DR: A timeout error is always caused, when a device doesn't answer, but it has nothing to do with the bacstack itself. Feel free to re-open if this issue still persists / is still relevant, even after following the tips in the FAQ.
