### ISSUE TITLE
how to subscribeProperty

### ISSUE THREAD

**Issue by duydatpham** [fh1ch/node-bacstack#125]
i'm researching BACnet protocol with this library. Now i need to subscribeProperty, but i don't know how to use.
Pls help me, can you share me a example to use ?
many thanks,

**Comment by fh1ch** [comment]
Hi @duydatpham. The `subscribeProperty` command is still in beta (see https://github.com/fh1ch/node-bacstack#features) and I didn't have the time so far to write compliance tests or add documentation. However, you can find the usage in the according integration test: https://github.com/fh1ch/node-bacstack/blob/master/test/integration/subscribe-property.spec.js. Documentation will be available as soon as the function is considered stable.

**Comment by NateZimmer** [comment]
I could not get subscribe property to work. I got bacnet error class 5 code 43... was rather cryptic. 

I could however get subscribeCOV to work which will update upon any COV... atleast how it was acting for me. The key was knowing to attach an event listener to `covNotifyUnconfirmed`

```js

var bacnetTimeoutMS = 6000;
var bacnetPort = 47808;

var client = new bacnet({ 'port': bacnetPort, 'apduTimeout': bacnetTimeoutMS });

client.on('error', function (e) {
    console.log(e);
});


client.subscribeCOV('192.168.4.16',{type: 0, instance: 1},55,false,false,100,0,(err,value)=>{
    console.log(err);
    console.log(value);
});


// COVs will go here 
client.on('covNotifyUnconfirmed',(data)=>{console.log(data)});
```
