### ISSUE TITLE
writeProperty increase counter twice - causing callback to fail

### ISSUE THREAD

**Issue by narbuzov** [fh1ch/node-bacstack#2]
in bacnet-client.js - writePropery function:
invokeCounter - being increased twice:
 
Once in line:
   baAdpu.encodeConfirmedServiceRequest(buffer, baEnum.BacnetPduTypes.PDU_TYPE_CONFIRMED_SERVICE_REQUEST, baEnum.BacnetConfirmedServices.SERV
ICE_CONFIRMED_WRITE_PROPERTY, maxSegments, baEnum.BacnetMaxAdpu.MAX_APDU1476, **invokeCounter++**, 0, 0);

Then:
**addCallback(invokeCounter++**, function(err, data) {

This causes callback to always timeout.

**Comment by fh1ch** [comment]
Hi @narbuzov 

Thank you very much for your bug report, I really appreciate this :+1:

The problem is now solved in the latest release "[0.0.1-beta.3](https://github.com/fh1ch/node-bacstack/blob/master/CHANGELOG.md#001-beta3-2017-04-14)".

Cheers
