### ISSUE TITLE
invokeID being sent higher than 255

### ISSUE THREAD

**Issue by nickngsr** [fh1ch/node-bacstack#22]
Firstly let me say, loving the work so far! Really useful library!

However we have hit a problem, the invokeCounter exceeds 255 and never gets reset. I have simply added a reset on the invokeCounter after 255 as that works fine for our use case (one device polling not so often), however it seems a bit 'hacky' as you could, quite legitimately (albeit unlikely), get a response from an earlier request with invokeID 0 after sending a request with an ID of 255, especially if you are talking to many devices.

Perhaps once the service is more complete and all responses are decoded the library can maintain an IP linked invokeID pool or similar?

Many thanks

**Comment by fh1ch** [comment]
Hi @nickngsr 

Sorry for the delayed response, I was away traveling. Also many thanks for the humbling words 😊 

Thanks for sharing this bug report, I really appreciate this 👍 This is indeed something I simply forgot to check, but which is resolved now with MR #23. It will be available in the upcoming release.

I also really like your idea with IP dependent invoke IDs, however I've never observed such a feature/behavior in other BACNET stacks/devices. This is surely something which I will investigate further and try to implement it, once the library is getting more stable.

Again, many thanks!

Cheers

**Comment by fh1ch** [comment]
Hi @nickngsr 

Sorry that I forgot to update this issue, but release 0.0.1-beta.8 is released now and contains the mentioned fix.
I furthermore copied your idea to issue #28.
I will therefore close this issue.

Again, thank you very much for this catch!

Cheers
