### ISSUE TITLE
RPM Returns back object

### ISSUE THREAD

**Issue by jscott3201** [fh1ch/node-bacstack#30]
First: Great work on this stack! Looking forward to using this more!

On the RPM call I receive an object back. Code samples with a Read Prop and RPM setup the same way

```
var bacnet = require('bacstack');

// Initialize BACStack
var client = bacnet({adpuTimeout: 6000});

// Read property

client.readProperty('192.168.7.72', 8, 240001, 77, null, function(err, value) {
  console.log(value);
});


// Read Property Multiple
// Setup array of reads here
var requestArray = [{objectIdentifier: {type: 8, instance: 240001}, propertyReferences: [{propertyIdentifier: 77}]}];

// Invoke RPM on BACnet Link
client.readPropertyMultiple('192.168.7.72', requestArray, function(err, value) {
  console.log(value);
  client.close();
});
```

Log Output: 
```
{ len: 34,
  objectId: { type: 8, instance: 240001 },
  property: { propertyIdentifier: 77, propertyArrayIndex: 4294967295 },
  valueList: [ { len: 25, type: 7, value: 'Removed sensitive information' } ] }
undefined
```

Any input if you need more to work from I can toss your way! Codebase is more stable hopefully I can contribute as well

**Comment by jscott3201** [comment]
Log of the (err) function: 

```
Error: ERR_TIMEOUT
    at Timeout._onTimeout (/Users/michaelscott/BACstack_nodemodule/lib/bacnet-client.js:51:16)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

```

**Comment by fh1ch** [comment]
Hi @jscott3201 

First of all, thanks for the humbling words 😊 I'm also looking forward to utilize the stack more and more. Also a big thanks for providing this bug report with all the information.

As the *readProperty* service seems to work fine but the *readPropertyMultiple* service shows clear signs of a timeout (no value object in the last log line -> `undefined` and a timeout error -> `Error: ERR_TIMEOUT`), my best guess here is that the device has sent either an BACNET abort or error message, which can't be handled by *node-bacstack* at this point of time (I already have an implementation for that locally, but didn't have time to test it). There are quiet a lot of reasons for that, which range from *readPropertyMultiple* being not supported by your devices, issues with the segmentation size (either ADPU window size or max segment count missmatch).

I will try to bring the BACNET error and abort handling in until upcoming Sunday, which should give you a more detailed error description, however it won't fix the root-cause of your issue.

If you already want to analyze this problem further and have some skills with [Wireshark](https://www.wireshark.org/download.html), I suggest to run a capture while using the code example and applying the `bacapp` filter to Wireshark. You should then see all telegrams sent from your PC to your device and vice versa, which *hopefully* shows you the root-cause of your problem.

Nevertheless, I will keep you updated regarding further activities.

Cheers

PS: I hope to release the first *stable* release of this stack until end of July and you're of course always invited to contribute whatever you want 😄

**Comment by jscott3201** [comment]
RPM does indeed work. I have some examples but I may open a pull request for a docker setup to enable using Steve Karg's C BACnet Server Example to query with this stack against. Running it in a VM now. Close this issue and open a PR soon for some examples and added documentation!

**Comment by fh1ch** [comment]
@jscott3201 thanks for the feedback. Such a test setup would be perfect 👍 

Already a big thanks from my side for your efforts!
