### ISSUE TITLE
Ability to unbind iAm listeners

### ISSUE THREAD

**Issue by ryanluton** [fh1ch/node-bacstack#64]
First of all, 
great work on this! 

Is there a way to unbind any iAm listeners that may be dead. I'm currently opening a ws connection from a client which calls whoIs and listens for responses. However once this is closed the iAm stays open, and eventually hits nodes MaxListenersExceededWarning.

Thanks much! 

```
app.ws('/api/whois', (ws, req) => {
  ws.on('message', msg => {
    const data = JSON.parse(msg);
    if (data.action && data.action === 'get') {
      // defines event listener
      bacstack.client.on('iAm', device =>
        ws.send(JSON.stringify(device), err => {
          return ErrorHandler(err);
        })
      );
      // fire BACnet whoIs
      bacstack.client.whoIs();
    }
  });

  // clean up after yourself?
  ws.on('close', function() {
    console.log('Client disconnected.');
    bacstack.client.removeListener('iAm', () => {
      // removeListener is NOT firing
    });
  });

  // TODO: better errorhandling
  ws.on('error', ErrorHandler);
});
```

**Comment by fh1ch** [comment]
Hi @ryanluton 

Thanks 😊 
All events in node-bacstack are created using the Node.js event API, which is part of it's core. The documentation how to remove a listener can be found here: https://nodejs.org/api/events.html#events_emitter_removelistener_eventname_listener

Your code would therefore look something like this:

```js
app.ws('/api/whois', (ws, req) => {
  const iamHandler = (device) => {
    ws.send(JSON.stringify(device), err => return ErrorHandler(err));
  };

  ws.on('message', msg => {
    const data = JSON.parse(msg);
    if (data.action && data.action === 'get') {
      // defines event listener
      bacstack.client.on('iAm', iamHandler);
      // fire BACnet whoIs
      bacstack.client.whoIs();
    }
  });

  // clean up after yourself?
  ws.on('close', () => {
    console.log('Client disconnected.');
    bacstack.client.removeListener('iAm', iamHandler);
  });

  // TODO: better error handling
  ws.on('error', errorHandler);
});
```

**Note:** The callback in `removeListener` *never* fires. It is only used to remove the passed callback-instance from the event-handler-list if it's existing there. Passing a new/anonymous callback will have no effect.
**Disclaimer:** I haven't tested the code example above.

Cheers

**Comment by fh1ch** [comment]
Since this project uses the default Node.js event API and so far no feedback was received, I'm going to close this issue.
