### ISSUE TITLE
writeProperty throws Exception when writing null to presentValue

### ISSUE THREAD

**Issue by lka** [fh1ch/node-bacstack#65]
tried to use 

`writeProperty (address, 4, objectInstance, 85, 12, [{ type: 9, value: null }], (err, val) => {}
`

in order to reset entry in priority Array and got an Exception **'buffer.Add is not a function'**
(yes I know that the type of BACNET_APPLICATION_TAG_NULL is 0, but this doesn't matter here)

this is at line 431 of master/lib/bacnet-asn1.js:
snip >>>>
```
var bacappEncodeApplicationData = module.exports.bacappEncodeApplicationData = function(buffer, value) {
  if (value.value === null) {
    buffer.Add(baEnum.BacnetApplicationTags.BACNET_APPLICATION_TAG_NULL);
    return;
  }

```

<<<< snip

**Comment by fh1ch** [comment]
Hi @lka 

Thank you very much for reporting this issue. I really appreciate this 👍 
Sorry for the delay on this, I don't have too much time working on such topics lately...
However, this issue has been fixed in PR #67 and is now available as release `0.0.1-beta.12`.

Happy coding 🍻
