### ISSUE TITLE
COV functionality

### ISSUE THREAD

**Issue by Klemensas** [fh1ch/node-bacstack#69]
Hi, thank you for your library and effort.

What's the state of COV implementation?
I see you've listed it as having some support but I'm not able to get it working.

Though I might be interpreting the functionality wrong as I'm finding it hard to simulate and test out BACnet devices in general.
https://github.com/fh1ch/node-bacstack/blob/master/lib/bacnet-client.js#L178
Here you seem to be calling `baServices.decodeCOVNotifyUnconfirmed` which doesn't exist and throws an error. Isn't this part supposed to be related to confirmed notifications?

**Comment by Babavali** [comment]
Hi thanks for the BACnet library, really helpful.
As i am new to BACnet and NodeJs need some help which will be highly appreciated.
Thanks in Advance.
With the library version 0.0.1beta13 can you please help me to undertand the implemention of subscribeCOV functionality.
I didnt find any documentation related to COV in documnetation guide.
My Assumption: subscribeCOV i can do after discovering device and from the client i can call 
client.subscribeCOV (); or do i need to call some event to get COV values.

And from the code i did found this 
 self.subscribeCOV = function(address, objectId, subscribeId, cancel, issueConfirmedNotifications, lifetime, options, next) {}
subscribeId ,issueConfirmedNotifications :  how will get this parameter from the device.
  
Thanks,
Babavali

**Comment by aniston** [comment]
Hello @Klemensas , I seen that you made a PR request to get COV working.

Do you have a sample implementation on how it can be used in practice ?

**Comment by msj-fr** [comment]
Hello,

I am using this execellent library for some time now, bu tI must admit it would be great to have COV implemented.

Maybe with a minimum of information (or a quick sample) I could give a hand on testing.

Thanks !
