### ISSUE TITLE
Expose server.close

### ISSUE THREAD

**Issue by goliatone** [fh1ch/node-bacstack#8]
Currently there is no clean way to close the UDP connection. `lib/bacnet-transport.js` does not expose the `server` instance (to close the connection it directly) nor does it expose a close method.

**Comment by fh1ch** [comment]
Hi @goliatone 

First of all, sorry for the delayed response, I'm currently quiet busy :smile:. Also a big thanks for your input.

Yes this is indeed a feature, which not implemented yet as the transport layer is quiet minimalistic at the moment. I will enhance it for the upcoming release. You can already use your own transport layer implementation (see [here](https://github.com/fh1ch/node-bacstack/blob/master/index.js#L15)) as a workaround.

Cheers

**Comment by fh1ch** [comment]
Hi @goliatone 

I'm very sorry for the late update on this, but the latest release contains now a close function (see https://github.com/fh1ch/node-bacstack/blob/master/CHANGELOG.md#001-beta9-2017-07-12).

Cheers
