### ISSUE TITLE
Check compliance with Core Infrastructure best practises

### ISSUE THREAD

**Issue by fh1ch** [fh1ch/node-bacstack#91]
To be a first class OSS project citizen, we shall check if this project complies with the [Core Infrastructure best practises](https://bestpractices.coreinfrastructure.org/).

**Comment by fh1ch** [comment]
We currently reached [![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/1508/badge)](https://bestpractices.coreinfrastructure.org/projects/1508) without filling out everything. I will continue with answering the question during the next opportunity.

**Comment by bufferoverflow** [comment]
Happy to see that you look at core infrastructure initiative!

btw, a project team mail address is required for the [CODE_OF_CONDUCT.md](https://github.com/fh1ch/node-bacstack/blob/master/CODE_OF_CONDUCT.md)

**Comment by fh1ch** [comment]
All best practises applied, which made sense to this project.
